/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2022-02-17 13:58:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.project_3.controller.ORSView;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.project_3.controller.ORSView");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <Head>\n");
      out.write("         <!-- Required meta tags -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("      <!--  This is for showing icon in title bar. -->  \n");
      out.write("      <link rel=\"stylesheet\" href=\"css/BackGround.css\">\n");
      out.write("     <title>ORS</title>\n");
      out.write("        <link rel=\"shortcut icon\" href=\"image/TitleIcon.png\" type=\"image/x-icon\">\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("        body{\n");
      out.write("        height:90%;\n");
      out.write("        background-image: url(\"./image/Gold.jpg\"); \n");
      out.write("         background-size:cover;\n");
      out.write("        background-repeat: no-repeat;\n");
      out.write("        align:centre;\n");
      out.write("        background-position:center; \n");
      out.write("       \n");
      out.write("        \n");
      out.write("       \n");
      out.write("       \n");
      out.write("       \n");
      out.write("        }\n");
      out.write("        </style>\n");
      out.write("        \n");
      out.write("    </Head>\n");
      out.write("    <body>\n");
      out.write("   <!--  <div class=\"bg\"> -->\n");
      out.write("\n");
      out.write("      \n");
      out.write("    <div class=\"logo\"  style=\"margin-left: 38%; margin-top: 10%\">\n");
      out.write("         <!--  <div class=\"w\" id=\"uperquote\"><font id=\"it\">Think IT </font>Think Us</div> -->\n");
      out.write("        <!-- <img src=\"image/sun.png\" id=\"sun\"> -->\n");
      out.write("      <font id=\"R\" color=\"blue\"; >R</font><font id=\"AYS\" color=\"blue\">AYS</font><div align=\"center\" style=\"margin-top:-8%; margin-left: 24%; color:white\" ><h1 >Presents</h1></div>\n");
      out.write("        <!-- <div class=\"w\" id=\"iso\">ISO 9001:2015 Company</div>\n");
      out.write("        <div class=\"w\" id=\"year\">Since 2006</div> -->\n");
      out.write("        \n");
      out.write("    </div> \n");
      out.write("   <!--  <br><br><br>\n");
      out.write("   <h1 align=\"Center\">\n");
      out.write("  <img src=\"image/rays.png\" width=\"318\" height=\"127\" border=\"0\">\n");
      out.write("</h1> -->\n");
      out.write("    \n");
      out.write("    <h1 align=\"Center\"  style=\"margin-bottom: 10%;\">\n");
      out.write(" <a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\"><font size=\"10px\" color=\"blue\">\n");
      out.write("	Online Result System \n");
      out.write(" </font></a>\n");
      out.write("</h1>\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- </div> -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
